### ISSUE TITLE
The error when simulating 

### ISSUE THREAD

**Issue by mendax1234** [4201VitruvianBots/2021SwerveSim#1]
It seems that l can't simulate it . 
![image](https://user-images.githubusercontent.com/62934294/124351330-476e1300-dc2c-11eb-9418-1207f3851aa6.png)

**Comment by jonathandao0** [comment]
So there are two code examples in this repository: Swerve2021 and WPILib_SwerveControllerCommand. You need to change directories to either of them and then run "cmd.exe /d /c simulateExternalJava" within it. If you plan on using WPILib's simulation software, you need to change the command to "cmd.exe /d /c simulateJava"

For the Swerve2021 example, I just tried to run it from a clean install and it is failing at the moment. The website hosting the libraries for the NavX seems to be down at the moment (nexus.otake.pw/repository/maven-public). It should come back up sometime later, but I don't know when that would be.

**Comment by mendax1234** [comment]
l have already split these two folders , but the error is same .

**Comment by jonathandao0** [comment]
I still can't seem to replicate the issue. Since you are able to able to run other projects successfully based on your Chief Delphi post, I would recommend creating a new Java robot project using the 2021 FRC WPILib VS Code project creator and then replace all of the *.java files under the src/ directory with the contents of one of the examples. For the Swerve2021 example, you will also need to copy over the contents of the venderdeps/ folder as well. Once you have done that, verify that it runs properly by running "cmd.exe /d /c simulateJava".

**Comment by mendax1234** [comment]
Ok and l will try it now

**Comment by mendax1234** [comment]
![image](https://user-images.githubusercontent.com/62934294/124527468-34c82980-de38-11eb-90c5-b2ae1b2b4991.png)
It seems that there is also something wrong with it .

**Comment by mendax1234** [comment]
It seems that it works well ! Emmm, so how can l replace it with my code , there seems to be many places l need to replace.
